services:
  db:
    container_name: mooburger-db
    environment:
      POSTGRES_DB: mooburger
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    image: postgres
    networks:
      - local
    ports:
      - 5432:5432
    restart: always
    volumes:
      - data:/data/postgres

networks:
  local:
    driver: bridge

volumes:
  data:
