services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: pnpm start:dev
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - local
    ports:
      - 3333:3333
    restart: always
    volumes:
      - .:/usr/app

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mooburger
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./tmp/data/pg:/data/postgres
    networks:
      - local

networks:
  local:
    driver: bridge
